### PR TITLE
Issue55

### PR DESCRIPTION
**Pull request by greenTara**
I am initiating a pull request back to you. So far I have included only the modification I suggested to the substructure of this profiles section. I would like to get feedback from you before modifying the terminology concerning the time series subprofiles.

### CODE REVIEW

**Comment by lisp** [comment]
in what way is 6.1.2 not already a consequence of the definition of an "rdf stream" earlier in the document?
in order for there to be something to restrict,  the abstract stream definition could allow <= which the 6.1.2 then restricts to <.
?

**Comment by lisp** [comment]
is the xsd:dateTimeStamp in the editor's note following example 8 correct?
should that not be xsd:dateTime?

**Comment by lisp** [comment]
i added a subsection about profile "profiles".

**Comment by greenTara** [comment]
Re: in what way is 6.1.2 not already a consequence of the definition of an "rdf stream" earlier in the document?

The RDF stream definition allows two (or more) elements of the stream to have the same timestamp, even when they use the same timestamp predicate. The definition only requires that **if** the timestamp of one element is later than the timestamp of another element (with the same timestamp predicate, e.g. as is required in the time series) **then** the elements must appear in the sequence in chronological order. But the definition does not require that for any two elements of the stream with the same timestamp predicate, one timestamp must be later than the other.

Re: is the xsd:dateTimeStamp in the editor's note following example 8 correct?
should that not be xsd:dateTime?

Yes, you are correct.

**Comment by greenTara** [comment]
Re: i added a subsection about profile "profiles".

The practical method of identifying the profile e.g. through media type is an important point. I am no expert on this, so I can't evaluate your proposal. The topic is not within the scope of this document, however. I suggest we make this an editor's note for now, so the idea doesn't get lost, because there is not yet an appropriate document to put it in.

As to the exact form of the identifier, is this following some W3C convention?

**Comment by lisp** [comment]
as the document says nothing about delivery - which, although quite unfortunate, is nothing i am about to contest, a note is certainly appropriate.
the approach is used in the json-ld recommendation, in the section on iaia considerations, where the media type is defined.
i do now know how standard the practice is.
as these would imply a profile argument on a media type, such as text/turtle, i suspect they would be viewed as suspect, but it makes sense, as it puts the qualification in the right place.

**Comment by greenTara** [comment]
Hi james - no one is saying delivery is out of scope for the group as a
whole, just that delivery is not part of this particular document, which is
only about Abstract Syntax and Semantics, not even about the concrete
serialization, which you have to have before you even think about delivery.
Also the query language, the real focus of the group, is out of scope for
this document. We are authoring modularly, and I assume we will merge all
these pieces together at the end. We are doing this because the group is
very diverse, with a lot of the active members being weak or uninterested
in theory, and so don't really want to be bothered with this topic.

Tara

**Comment by lisp** [comment]
ok, then this concrete form does not belong there at all.
still, there should be some mention in the document, that a stream must be associated with some indication of its profile. somehow.
a similar issues applies to specifying the concrete predicate which is to indicate the timestamp.

**Comment by greenTara** [comment]
Yes, that's a good way to create a cross-reference to the document (future, section of larger document) to the concrete semantics and delivery considerations.

To say this carefully, I would say "In order to take advantage of the specialized algorithms applicable to a profile, it is necessary to identify the intended profile to the recipient. This aspect is not part of the abstract syntax itself, but is addressed in @@@"

where @@@ is the W3C convention for a placeholder.

**Comment by greenTara** [comment]
Are we going to try for a pull request on this to streamreasoning before
the call today?

Tara

**Comment by greenTara** [comment]
I just realized that was a silly question - we already have a pull request
for this https://github.com/streamreasoning/RSP-QL/pull/59

What I should have said is "Are we going to try to add any more commits to
this pull request before the meeting today?"

Tara

**Comment by greenTara** [comment]
I think we could pull your last two commits, and then I can change the
style of the paragraph about media types to "ednote".

**Pull request merged**
